apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bouncing-balls-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: bouncing-balls
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: bouncing-balls/application-mainfest
    repoURL: https://github.com/ksingh7/argocd-openshift
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true